name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Mac
      run: dotnet publish ./src/GiveMe/GiveMe.csproj --configuration release --runtime osx-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --output ./mac
    - name: Zip Mac
      run: zip -r mac.zip mac
    - name: Publish Windows
      run: dotnet publish ./src/GiveMe/GiveMe.csproj --configuration release  --runtime win10-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --output ./windows
    - name: Zip Windows
      run: zip -r windows.zip windows
    - name: Publish Ubuntu
      run: dotnet publish ./src/GiveMe/GiveMe.csproj --configuration release --runtime ubuntu-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --output ./ubuntu
    - name: Zip Ubuntu
      run: zip -r ubuntu.zip ubuntu
    - name: Publish ARM64
      run: dotnet publish ./src/GiveMe/GiveMe.csproj --configuration release  --runtime linux-arm64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --output ./arm-64
    - name: Zip Ubuntu
      run: zip -r ubuntu.zip ubuntu